// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:         string;
    type:       string;
    place_type: string[];
    relevance:  number;
    properties: Properties;
    text:       string;
    place_name: string;
    center:     number[];
    geometry:   Geometry;
    context:    Context[];
}

export interface Context {
    id:          string;
    mapbox_id:   string;
    text:        string;
    wikidata?:   Wikidata;
    short_code?: ShortCode;
}

export enum ShortCode {
    MX = "mx",
    MXMor = "MX-MOR",
}

export enum Wikidata {
    Q602729 = "Q602729",
    Q66117 = "Q66117",
    Q96 = "Q96",
}

export interface Geometry {
    type:        string;
    coordinates: number[];
}

export interface Properties {
    accuracy:   string;
    mapbox_id?: string;
}
